version: '3.9' # optional since v1.27.0
services:
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '/app/node_modules'
      - './:/app'
